apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-f5-hello
  namespace: nginx-ingress
  labels:
    cis.f5.com/as3-tenant: AS3
    cis.f5.com/as3-app: A1
    cis.f5.com/as3-pool: web_pool
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-ingress

