---

- name: Prep Ubuntu
  hosts: kube_all
  become: yes
  tasks:
  - import_tasks: update-ubuntu.yaml
  - import_tasks: update-hosts.yaml
  - import_tasks: install-docker.yaml
  - import_tasks: prep-kube.yaml

- name: Initialize Master
  hosts: kube_masters
  become: yes
  gather_facts: no
  tasks:
  - import_tasks: kube-master.yaml

- name: Initialize Nodes
  hosts: kube_nodes
  become: yes
  gather_facts: no
  tasks:
  - import_tasks: kube-node.yaml
