apiVersion: v1
kind: ConfigMap
metadata:
  name: f5-hello-world
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
    template: |
      {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.17.0",
            "label": "f5-hello-world",
            "remark": "Simple HTTP Hello World",
            "AS3": {
                "class": "Tenant",
                "A1": {
                    "class": "Application",
                    "template": "generic",
                    "iningress": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.1.1.4"
                        ],
                        "remark":"ingress: f5-hello-world",
                        "virtualPort": 81,
                        "pool": "hello-world_pool"
                    },
                    "hello-world_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
