---

- name: Install Apache on kube-master1
  hosts: kube-master1

  tasks:
    - name: Install apache
      become: true
      apt:
        name: apache2
        update_cache: yes
        state: present
