---

- name: Install Docker
  hosts: kube-all

  tasks:
    - name: Add docker GPG key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repo
      become: true
      apt_repository:
        filename: docker
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        state: present
    - name: Install docker-ce
      become: true
      apt:
        name: docker-ce
        update_cache: yes
        state: present
    - name: Update cgroupdriver
      become: true
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
          "exec-opts": ["native.cgroupdriver=cgroupfs"]
          }

