---

- name: Disable swap file permanantly 
  hosts: kube-all

  tasks:
    - name: Remove swapfile from /etc/fstab
      become: true
      replace:
        dest: /etc/fstab
        backup: yes
        regexp: '(^UUID=.*none.*swap.*)'
        replace: '#\1'
    - name: Disable swap
      become: true
      command: swapoff -a
      when: ansible_swaptotal_mb > 0
