kind: ConfigMap
apiVersion: v1
metadata:
  name: vs-f5-demo-app
  namespace: f5demo
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "serviceName": "f5-demo-app",
          "servicePort": 8080
        },
        "frontend": {
          "partition": "ocp",
          "iapp": "/Common/f5.http.v1.3.0rc3",
          "iappPoolMemberTable": {
            "name": "pool__members",
            "columns": [
                {"name": "addr", "kind": "IPAddress"},
                {"name": "port", "kind": "Port"},
                {"name": "connection_limit", "value": "0"}
            ]
          },
          "iappOptions": {
            "description": "myService_f5.http iApp"
          },
          "iappVariables": {
            "monitor__monitor": "/#create_new#",
            "monitor__response": "none",
            "monitor__uri": "/",
            "net__client_mode": "wan",
            "net__server_mode": "lan",
            "pool__addr": "10.10.201.130",
            "pool__pool_to_use": "/#create_new#",
            "pool__port": "80"
          }
        }
      }
    }
