name: Build the Docs
on: [push]
jobs:
  build-the-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.2.1
    - run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run container build script
      run: ./containthedocs-build.sh
      shell: bash
